name: Deploy to Test Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Configure Git for test-repo push
      run: |
        echo "https://x-access-token:${{ secrets.TEST_REPO_PAT }}@github.com" > ~/.git-credentials
        git config --global credential.helper store

    - name: Add test-repo remote and push
      run: |
        git remote add test-repo https://github.com/Ali-ISAA/test-repo.git
        git push test-repo main
