name: Deploy to Test Repo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Push to test-repo using GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.TEST_REPO_PAT }}
      run: |
        # Configure git
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        
        # Use GitHub CLI to push
        gh auth setup-git
        git remote add test-repo https://github.com/Ali-ISAA/test-repo.git
        git push test-repo main --force
        #test