name: Deploy to Test Repo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Deploy to test-repo using PAT
      env:
        PAT_TOKEN: ${{ secrets.TEST_REPO_PAT }}
      run: |
        # Configure git globally
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

        # Clone test-repo
        git clone https://oauth2:${PAT_TOKEN}@github.com/Ali-ISAA/test-repo.git test-repo-temp

        # Remove everything except .git, .github, and README.md from test-repo
        cd test-repo-temp
        find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'README.md' -exec rm -rf {} +

        # Copy all files from dev-repo except .github and README.md
        cd ..
        rsync -av --exclude='.git' --exclude='.github' --exclude='README.md' --exclude='test-repo-temp' . test-repo-temp/

        # Commit and push changes
        cd test-repo-temp
        git add -A
        git diff --staged --quiet || git commit -m "Deploy from dev-repo (excluding .github workflows)"
        git push origin main