name: Deploy to Test Repo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Push to test-repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TEST_REPO_PAT }}
        repository: Ali-ISAA/test-repo
        branch: main