name: Deploy to Test Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Add test-repo remote and push
      env:
        GH_TOKEN: ${{ secrets.TEST_REPO_PAT }} # Ensure PAT is available as an environment variable
      run: |
        git remote add test-repo https://x-access-token:$GH_TOKEN@github.com/Ali-ISAA/test-repo.git
        git push test-repo main
