name: Deploy to Test Repo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        
    - name: Debug and Add test-repo remote
      env:
        GH_TOKEN: ${{ secrets.TEST_REPO_PAT }}
      run: |
        echo "Token length: ${#GH_TOKEN}"
        echo "Token starts with: ${GH_TOKEN:0:4}"
        
        # Remove any existing test-repo remote
        git remote remove test-repo 2>/dev/null || true
        
        # Add test-repo with authentication
        git remote add test-repo "https://x-access-token:${GH_TOKEN}@github.com/Ali-ISAA/test-repo.git"
        
        # Show the remote URL (it will be masked)
        echo "Remote URL set:"
        git remote -v
        
    - name: Push to test-repo
      run: |
        git push test-repo main --force