name: Deploy to Test Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Add test-repo remote and push
      env:
        TEST_REPO_URL: "https://github.com/Ali-ISAA/test-repo.git" # Assuming test-repo is also on GitHub
        GITHUB_TOKEN: ${{ secrets.TEST_REPO_PAT }}
      run: |
        git remote add test-repo $TEST_REPO_URL
        git -c "http.https://github.com/.extraheader=AUTHORIZATION: Basic $(echo -n x-access-token:$GH_TOKEN | base64)" push test-repo main
